apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^process/(?P<typelogin>(login)|(register))$', views.process, name = 'process'),
    url(r'^logout$', views.logout, name = 'logout')
]

trail_of_turkeys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^', include('apps.logreg.urls', namespace = 'logreg')),
	url(r'^turkeytrail/', include('apps.turkeytrail.urls', namespace = 'turkeytrail')),
    url(r'^turkey_blackjack/', include('apps.turkey_blackjack.urls', namespace = 'turkey_blackjack')),
]

apps/logreg/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

class UserManager(models.Manager):
	def validator(self, postData, typelogin): #validates login/registration informtaion
		NAME_REGEX = re.compile(r'^[a-zA-Z\-\']{2,}$')
		USERNAME_REGEX = re.compile(r'(?=^.{3,}$)(?=.*\d)*(?=.*[a-z])*(?=.*[A-Z])*(?=.*[!@#$%^&amp;*()_+}{&quot;:;\'?/&gt;.&lt;,])*(?!.*\s)*.*$')
		EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
		PWORD_REGEX = re.compile(r'(?=^.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&amp;*()_+}{&quot;:;\'?/&gt;.&lt;,])(?!.*\s).*$')
		errors = {
			'reg' : [],
			'login' : [],
		} #empty dictionary to push errors to for registration, password, and login attempts
		result = {} #empty dictionary to store return values

		if typelogin == 'register': #if the user is trying to register...
			try: #attempt to retrieve user information based on the email they entered
				validuser = self.get(email = postData['email'])
			except User.DoesNotExist: #set validuser to none if it isn't able to retrieve anything
				validuser = None

			if validuser: #if able to retrieve a user from the database based on the entered email address...
				errors['reg'].append('This email has already been registered.')
			if '' in (postData['first_name'], postData['last_name'], postData['email'], postData['password'], postData['confirm']): #if any of the fields are left blank...
				errors['reg'].append('Please fill in all fields.')
			if not NAME_REGEX.match(postData['first_name']): #if the first name isn't a valid format
				errors['reg'].append('Please enter a valid first name.')
			if not NAME_REGEX.match(postData['last_name']): #if the last name isn't a valid format
				errors['reg'].append('Please enter a valid last name.')
			if not USERNAME_REGEX.match(postData['username']): #if the username isn't a valid format
				errors['reg'].append('Please enter a valid username (Must be at least 3 characters in length).')
			if not EMAIL_REGEX.match(postData['email']): #if the email isn't a valid format
				errors['reg'].append('Please enter a valid email address.')
			if not PWORD_REGEX.match(postData['password']): #if the password doesn't meet the minimum requirements
				errors['reg'].append('Password must be at least 8 characters and contain one uppercase letter, one lowercase letter, one number, and one special character.')
			if postData['password'] != postData['confirm']: #if the password and password confirmation don't match
				errors['reg'].append('Password and confirmation password do not match.')

		elif typelogin == 'login': #if the user is trying to login...
			try: #attempt to retrieve the user information based on the entered email address
				loginuser = self.get(email = postData['email'])
			except User.DoesNotExist: #if the entered email address isn't in the system, set loginuser to none
				loginuser = None

			if not loginuser: #if the entered email address isn't in the database...
				errors['login'].append('Please enter a registered email and/or valid password.')
			elif not bcrypt.hashpw(postData['password'].encode(), loginuser.password.encode()) == loginuser.password.encode(): #if the password doesn't match the one for the user in the database...
				errors['login'].append('Please enter a registered email and/or valid password.')

		if not errors['reg'] and not errors['login']: #if there are no errors...
			if typelogin == 'register': #and the user is registering
				user = self.creator(postData) #create the user using the creator method below and store the user information returned as user
			elif typelogin == 'login': #if the user is logging in
				user = self.get(email = postData['email']) #retrieve that user's information and store is as user
			result['loggedin'] = True #set the user's logged in status to true and store it in the result dictionary
			result['user'] = user #store the user information in the result dictionary

		else: #however, if there ARE errors...
			result['loggedin'] = False #set the user's logged in status to false and store it in the result dictionary
			result['errors'] = errors #store the errors in the result dictionary

		return result #return the result dictionary

	def creator(self, data): #creates the user in the database based on the appropriately entered registration information
		new_user = self.create(first_name = data['first_name'], last_name = data['last_name'], username = data['username'], email = data['email'], password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt()), money = 20)
		return new_user #return the newly created user's information

class User(models.Model):
	first_name = models.CharField(max_length = 55)
	last_name = models.CharField(max_length = 100)
	username = models.CharField(max_length = 100)
	email = models.EmailField(max_length = 254)
	password = models.CharField(max_length = 255)
	money = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = UserManager()

apps/logreg/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User

def index(request):
	return render(request, 'logreg/index.html')

def process(request, typelogin): #route to process the entered information if a user attempts to log in or register
	result = User.objects.validator(request.POST, typelogin) #get a result based on the user's entered information
	request.session['loggedin'] = result['loggedin'] #store whether or not the user is logged in in session

	if result['loggedin']: #if the user is logged in based on the entered information...
		request.session['user'] = result['user'] #store the user's information in session
		return redirect(reverse('turkeytrail:index')) #redirect the user to the success route
	else: #if the user is not logged in based on the entered information...
		for error in result['errors']['reg']: #for every error...
			messages.error(request, error) #make a flash message
		for warning in result['errors']['login']:
			messages.warning(request, warning)
		return redirect(reverse('logreg:index')) #redirect back to root

def logout(request):
	request.session['loggedin'] = False #log the user out
	del request.session['user']
	return redirect('logreg:index') #redirect to root

apps/logreg/templates/logreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="description" content="Coding Dojo Turkey Day Hackstravaganz-hack Thanksgiving Trail of Turkeys">
	{% load staticfiles %}
	<title>Thanksgiving Trail of Turkeys</title>
	<link rel="stylesheet" href="{% static 'logreg/css/css_boilerplate.css' %}" media="screen">
	<style media="screen">
		#title{
			margin-top: 6%;
			font-family: "Courier New", Courier, monospace;
			font-size: 500%;
			color: yellow;
			text-shadow: 4px 4px #f00000;
		}
		.minititle{
			font-family: "Courier New", Courier, monospace;
			color: rgb(200, 76, 6);
			text-shadow: 1px 1px #f00000;
		}
		section {
			display: inline-block;
			vertical-align: middle;
		}
		.sixty {
			width: 58%;
		}
		.hidden {
			display: none;
		}
		h1 {
			text-align: center;
		}
		main section:first-child {
			border-right: 1px solid gray;
			padding-left: 40px;
			padding-right: 50px;
		}
		main section:last-child {
			padding-left: 40px;
			padding-right: 50px;
			width: 49%;
		}
		#pworderror {
			border: 1px solid gray;
			padding: 5px;
			color: red;
			font-size: .9em;
		}
	</style>
</head>
<body>
	<h1 id="title">Trail of Turkeys</h1>
	<main class="eighty">
		<section class="fifty">
			<h1 class="minititle">Register</h1>
			{% if messages %}
				<div class="notif">
					{% for message in messages %}
						{% if message.tags == "error" %}
							<p class="red">{{ message }}</p>
						{% endif %}
					{% endfor %}
				</div><!-- end_of_notif red-->
			{% endif %}
			<form class="hundo" action="{% url 'logreg:process' typelogin='register' %}" method="post">
				{% csrf_token %}
				<label class="forty" for="first_name">First Name:</label>
				<input id="first" class="sixty" type="text" name="first_name">
				<label class="forty" for="last_name">Last Name:</label>
				<input class="sixty" type="text" name="last_name" >
				<label class="forty" for="username">Username:</label>
				<input class="sixty" type="text" name="username" >
				<label class="forty" for="email">Email Address:</label>
				<input class="sixty" type="text" name="email">
				<label class="forty" for="password">Password:</label>
				<input id="password" class="sixty" type="password" name="password" onkeyup="checkPword()" onkeydown="checkPword()">
				<p id="pworderror" class="hidden"><em></em></p>
				<label class="forty" for="confirm">Confirm Password:</label>
				<input id="confirm" class="sixty" type="password" name="confirm" onkeyup="checkConf()" onkeydown="checkConf()">
				<input class="btn btn-pop" type="submit" name="register" value="Register">
			</form>
		</section>
		<section class="right">
			<h1 class="minititle">Login</h1>
			{% if messages %}
				<div class="notif">
					{% for message in messages %}
						{% if message.tags == "warning" %}
							<p class="red">{{ message }}</p>
						{% endif %}
					{% endfor %}
				</div><!-- end_of_notif red-->
			{% endif %}
			<form class="hundo" action="{% url 'logreg:process' typelogin='login' %}" method="post">
				{% csrf_token %}
				<label class="forty" for="email">Email Address:</label>
				<input class="sixty" type="text" name="email">
				<label class="forty" for="password">Password:</label>
				<input class="sixty" type="password" name="password">
				<input class="btn btn-pop" type="submit" name="login" value="Login">
			</form>
		</section>
	</main>
	<script type="text/javascript">
		var pwordError = document.getElementById('pworderror'),
		first = document.getElementById('first'),
		pword = document.getElementById('password'),
		conf = document.getElementById('confirm'),
		pwordReg = /(?=^.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{:;'?/><.;,])(?!.*\s).*$/;
		function checkPword() { //allows the password error box to be dynamically rendered and adds a red or green border to the password input based on the password entered matching the given regex
			if (pword.value.match(pwordReg)) {
				pwordError.className = "hidden";
				pword.style.border = "3px solid green";
			} else {
				pwordError.innerHTML = "Password must be at least 8 characters and contain one uppercase letter, one lowercase letter, one number, and one special character.";
				pwordError.className = "";
				pword.style.border = "3px solid red";
			}
		}
		function checkConf() { //outlines the confirm password input based on it matching the password input
			if (conf.value == pword.value && conf.value.match(pwordReg)) {
				conf.style.border = "3px solid green";
			} else {
				conf.style.border = "3px solid red";
			}
		}
		first.focus(); //on page load, puts the cursor in the register first name input field
	</script>
</body>
</html>