apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^process/(?P<typelogin>(login)|(register))$', views.process, name = 'process'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/turkeytrail/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
	url(r'^roll$', views.roll, name = "roll"),
]

trail_of_turkeys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^', include('apps.logreg.urls', namespace = 'logreg')),
	url(r'^turkeytrail/', include('apps.turkeytrail.urls', namespace = 'turkeytrail')),
    url(r'^turkey_blackjack/', include('apps.turkey_blackjack.urls', namespace = 'turkey_blackjack')),
]

apps/turkeytrail/models.py
from django.db import models
import json, collections
from jsonfield import JSONField
from ..logreg.models import User

class CharDBManager(models.Manager):
	class Character(object):
		def __init__(self, name, special, luck, beer_stamina, damage):
			self.special = special
			self.luck = luck
			self.damage = damage
			self.name = name
			self.beer_stamina = beer_stamina
			self.sobriety = 100
			self.health = 100
			self.money = 20
			self.tryptophan = 0
			self.family = {
				'dad' : {
					'health' : 100,
					'beer_stamina' : 4,
					'sobriety' : 100,
					'damage' : 4
				},
				'mom' : {
					'health' : 100,
					'beer_stamina' : 3,
					'sobriety' : 100,
					'damage' : 3,
				},
					'bro' : {
					'health' : 100,
					'beer_stamina' : 2,
					'sobriety' : 100,
					'damage' : 2,
				},
					'sis' : {
					'health' : 100,
					'beer_stamina' : 2,
					'sobriety' : 100,
					'damage' : 2,
				},
					'dog' : {
					'health' : 100,
					'beer_stamina' : 1,
					'sobriety' : 100,
					'damage' : 2,
				},
			}

	def createCharacter(self, name):
		chardict = {
			'josiah' : Character('Josiah', 'Bible', 3, 2, 1),
			'samuel' : Character('Samuel', 'Drinking', 1, 3, 2),
			'benjamin' : Character('Benjamin', 'Fighting', 2, 1, 3),
			'isabelle' : Character('Isabelle', 'Cats', 1, 2, 3),
			'emily' : Character('Emily', 'Nun', 3, 1, 2),
			'sarah' : Character('Sarah', 'Nurse', 2, 3, 1),
			'madjack' : Character('MadJack', 'Coding Wizard', 4, 4, 4),
		}
		character = chardict.name

	def populateDB(self, character):
		self.create(name = character.name, luck = character.luck, money = character.money, beer_stamina = character.beer_stamina, damage = character.damage, special = character.special, sobriety = character.sobriety, health = character.health, tryptophan = character.tryptophan, family = json.dumps(character.family))
		return self

class CharDB(models.Model):
	name = models.CharField(max_length = 10)
	person = models.ForeignKey(User, on_delete = models.CASCADE)
	luck = models.IntegerField()
	money = models.IntegerField()
	beer_stamina = models.IntegerField()
	damage = models.IntegerField()
	special= models.CharField(max_length = 15)
	sobriety = models.IntegerField()
	health = models.IntegerField()
	tryptophan = models.IntegerField()
	family = JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = CharDBManager()

apps/turkeytrail/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

def index(request):
	if not request.session['loggedin']:
		return redirect(reverse('logreg:index'))

	context = {
		'characters' : ['Josiah', 'Isabelle', 'Benjamin', 'Emily', 'Samuel', 'Sarah']
	}
	return render(request, 'turkeytrail/splash.html', context)

def roll(request):
	return redirect(request, 'turkeytrail:index')

apps/turkeytrail/templates/turkeytrail/splash.html
<!DOCTYPE html>
<html>
  <head>
    <title>Turkeys about TK all over you</title>
  <style type="text/CSS">
  #background {
    background-image: url("https://motorcyclephotooftheday.files.wordpress.com/2011/11/drunk-turkey.jpg");
    opacity: .2;
    width: 100%;
    height: 100%;
    position: absolute;
    z-index: -1;
  }
  h3{
    z-index:1;
  }
  h1{
    margin-top: 5%;
    font-family: "Courier New", Courier, monospace;
    font-size: 400%;
    color: yellow;
    text-shadow: 4px 4px #f00000;
  }
  body{
    text-align: center;
  }
  h4{
    margin-top: 5%;
    font-family: "Courier New", Courier, monospace;
    font-size: 150%;
    color: yellow;
    text-shadow: 2px 2px #f00000;
  }
  input{
    background: linear-gradient(lightgray, red 30%);
    color: yellow;
    padding: 5px;
    border-radius: 5px;
  }
  input:hover {
	cursor: pointer;
	box-shadow: 1px 1px 3px black;
}
  h3{
    border-style: groove;
    border-color: #f00000;
    background: linear-gradient(brown,yellow 70%);
  }

  </style>
  <script type="text/javascript">
  </script>
  </head>
<body>
  <div id="background">
  </div>
  <h1>Welcome to the Thanksgiving trail of Turkeys!</h1><h3> You and your family need to make a journey from your home, over the river, through the woods and to Grandmother’s house to enjoy a splendiferous Thanksgiving Day feast and become victorious in Grandma’s Annual Flip Cup Contest. Along the way, you will encounter Thanksgiving related trials and tribulations that will transform you into the Thanksgiving Day warrior you know you could be. Prepare yourself for the festivities.</h3>
    <h4>Choose your Character</h4>
    <form action="{% url 'turkeytrail:roll'%}" method="POST">
      {% csrf_token %}
      <label for="players">Character: </label>
	  <select name="players">
      {% for character in characters %}
      <option value="{{character}}">{{character}}</option>
      {% endfor %}
    	</select>
      <p><input type="submit" value="Let's Eat!"></p>
    </form>
		<a href="{% url 'turkey_blackjack:index' %}"><strong>Play Turkey BJ</strong></a>
        <a href="{% url 'logreg:logout' %}"><strong>Log out</strong></a>
</body>
</html>