apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^process/(?P<typelogin>(login)|(register))$', views.process, name = 'process'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/turkey_blackjack/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
	url(r'^home$', views.home, name = "home")
]

trail_of_turkeys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^', include('apps.logreg.urls', namespace = 'logreg')),
	url(r'^turkeytrail/', include('apps.turkeytrail.urls', namespace = 'turkeytrail')),
    url(r'^turkey_blackjack/', include('apps.turkey_blackjack.urls', namespace = 'turkey_blackjack')),
]

apps/turkey_blackjack/models.py
from django.db import models
import random

# Create your models here.

apps/turkey_blackjack/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from ..logreg.models import User

# Create your views here.

def index(request):
	if request.session['loggedin'] == False:
		return redirect(reverse('logreg:index'))
	context = {
		'user' : request.session['user'],
		'money' : User.objects.get(id = request.session['user'].id).money
	}
	print (request.session['user'].money)
	return render(request, "turkey_blackjack/index.html", context)

def home(request):
	User.objects.filter(id = request.session['user'].id).update(money = request.POST['money'])
	request.session['user'].money = request.POST['money']
	return redirect(reverse('turkeytrail:index'))

apps/turkey_blackjack/templates/turkey_blackjack/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load staticfiles %}
  <title>Turkey Black Jack</title>
  <link rel="stylesheet" href="{% static 'turkey_blackjack/css/styles.css' %}" media="screen">
  <style media="screen">
    #title{
      margin-top: 1%;
      font-family: "Courier New", Courier, monospace;
      font-size: 500%;
      color: yellow;
      text-shadow: 4px 4px #f00000;
      text-align: center;
    }
  </style>
</head>
<body>
  <header class="hundo">
    <a class="btn btn-imp right" id="logout" href="{% url 'logreg:logout' %}">Logout</a>
    <form class="right" id="home" action="{% url 'turkey_blackjack:home' %}" method="POST">
      <input type="hidden" id="mon" name="money" value="{{money}}">
      {% csrf_token %}
      <input class="btn btn-imp" type="submit" value="Home">
    </form>
    <h1 id="title" class="seventy center">Turkey Blackjack</h1>
  </header>
  <main>
    <div id="dealerHand"></div>
    <p id="message" class="theme"></p>
    <div id="yourHand" class="center"></div>
    <!-- <div id="yourScore">Your Score: <span class="digits">0</span> Record: <span id="wins">0</span>&nbsp;/&nbsp;<span id="losses">0</span></div> -->
    <div id="moves" class="ninety center">
      <div id="buttons" class="sixty left">
        <button class="btn btn-pop left" id="deal">Deal</button>
        <button class="btn btn-imp hidden left" id="hit">Hit</button>
        <button class="btn btn-imp hidden left" id="splity">Yes</button>
        <button class="btn btn-imp hidden left" id="splitn">No</button>
        <button class="btn btn-dflt hidden left" id="dbl">Double Down</button>
        <button class="btn btn-dflt hidden left" id="stay">Stay</button>
        <button class="btn btn-dflt hidden left" id="reset">Start Over</button>
      </div><!-- end_of_buttons-->
        <div id="betwrapper" class="thirty right">
          <span id="money" class="left theme" >Your Money: <span id="monies" class="theme">{{ money }}</span></span>
          <label class="fifty theme" for="bet">Your Bet:</label>
          <input id="bet" class="forty" type="number" name="bet" min="1" max="20" value="5">
        </div><!-- end_of_betwrapper-->
    </div>
  </main>
  <script src="{% static 'turkey_blackjack/js/turkey_blackjack.js' %}" type="text/javascript"></script>
</body>
</html>